services:
  postgres-wallet:
    image: postgres:18.0-bookworm
    container_name: postgres-xpay-wallet
    environment:
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
      POSTGRES_DB: xpay-db-wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_wallet_data:/var/lib/postgresql
    networks:
      - xpay-wallet-net

volumes:
  postgres_wallet_data:

networks:
  xpay-wallet-net:
    driver: bridge
