services:
  postgres-transactions:
    image: postgres:18.0-bookworm
    container_name: postgres-xpay-transactions
    environment:
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
      POSTGRES_DB: xpay-db-transactions
    ports:
      - "5434:5432"
    volumes:
      - postgres_transactions_data:/var/lib/postgresql
    networks:
      - xpay-transactions-net

volumes:
  postgres_transactions_data:

networks:
  xpay-transactions-net:
    driver: bridge
