services:
  kafka:
    image: confluentinc/cp-kafka:8.0.1
    container_name: kafka-kraft-xpay
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: 123e4567-e89b-12d3-a456-426614174000
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - xpay-net

  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus-xpay
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-storage:/prometheus
    networks:
      - xpay-net

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana-xpay
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - xpay-net
    depends_on:
      - prometheus

volumes:
  kafka_data:
  prometheus-storage:
  grafana-storage:

networks:
  xpay-net:
    driver: bridge
