services:
  postgres-auth:
    image: postgres:18.0-bookworm
    container_name: postgres-xpay-auth
    environment:
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
      POSTGRES_DB: xpay-db-auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql
    networks:
      - xpay-auth-net

volumes:
  postgres_auth_data:

networks:
  xpay-auth-net:
    driver: bridge
