services:
  postgres-user:
    image: postgres:18.0-bookworm
    container_name: postgres-xpay-user
    environment:
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
      POSTGRES_DB: xpay-db-user
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql
    networks:
      - xpay-user-net

volumes:
  postgres_user_data:

networks:
  xpay-user-net:
    driver: bridge
